### ISSUE TITLE
Support for definition lists

### ISSUE THREAD

**Issue by mavam** [sunaku/md2man#20]
Does support for description lists exist for roff output? I tried the [markdown extra syntax](https://michelf.ca/projects/php-markdown/extra/#def-list) but did not see an effect. I'd be nice to have that feature, as it is available in [ronn](https://rtomayko.github.io/ronn/ronn-format.7.html#DEFINITION-LISTS).

**Comment by sunaku** [comment]
AFAIK [indented paragraphs](https://sunaku.github.io/md2man/man/man5/md2man.5.html#indented-paragraphs) are the closest things to definition lists in Roff.

**Comment by mavam** [comment]
I see. One question regarding the output generation: is the following expected behavior?

The markdown code

```
`foo`
   f
   fo
   foo

  `bar` 
   b
   ba
   bar

`baz`
 b
 ba
 baz
```

yields a man page of the form

```
       foo
          f
          fo
          foo

       bar       b
                 ba
                 bar

       baz b ba baz
```

and in roff:

```roff
\fB\fCfoo\fR
   f
   fo
   foo
.TP
\fB\fCbar\fR 
   b
   ba
   bar
.PP
\fB\fCbaz\fR
b
ba
baz
```

**Comment by sunaku** [comment]
Yes, that is as expected:
* Your first paragraph is a [tagged paragraph](https://sunaku.github.io/md2man/man/man5/md2man.5.html#tagged-paragraphs) which is most similar to the definition list you seek
* Your second paragraph is an [indented paragraph](https://sunaku.github.io/md2man/man/man5/md2man.5.html#indented-paragraphs)
* Your third paragraph is a [normal paragraph](https://sunaku.github.io/md2man/man/man5/md2man.5.html#normal-paragraphs)

**Comment by mavam** [comment]
Okay, perfect. I think this is close enough to definition lists and works for me.

I'll close the ticket for now.
