### ISSUE TITLE
Not installable with gem

### ISSUE THREAD

**Issue by rockdaboot** [sunaku/md2man#23]
I would like to love md2man... but on Debian Sid I get:
```
$ sudo gem install md2man
Fetching: opener-0.1.0.gem (100%)
Successfully installed opener-0.1.0
Fetching: binman-5.1.0.gem (100%)
ERROR:  While executing gem ... (Gem::Package::PathError)
    installing into parent path /var/lib/gems/2.3.0/README.markdown of /var/lib/gems/2.3.0/gems/binman-5.1.0 is not allowed
```

Sorry, but I am absolutely not into Ruby/gems... what can I do ?

**Comment by sunaku** [comment]
Thanks for your report. :+1: This is [a known issue](https://github.com/rubygems/rubygems/issues/1448) that can be solved by upgrading to RubyGems 2.5.2:

    gem update --system

**Comment by rockdaboot** [comment]
Thanks, perfect !

**Comment by sunaku** [comment]
Good news for the future: [Ruby 2.3.2+ now includes RubyGems 2.5.2](https://www.ruby-lang.org/en/news/2016/11/15/ruby-2-3-2-released/) so you won't hit this problem anymore.
