### ISSUE TITLE
md2man fails to install on macOS with Homebrew ruby

### ISSUE THREAD

**Issue by fmeunier** [sunaku/md2man#24]
As per subject - I'm trying to install on macOS Sierra with ruby 2.3.1p112 from Homebrew. I get the following errors, any suggestions on resolving?

```
$ gem install md2man
ERROR:  While executing gem ... (Gem::Package::PathError)
    installing into parent path /usr/local/lib/ruby/gems/2.3.0/README.markdown of /usr/local/lib/ruby/gems/2.3.0/gems/binman-5.1.0 is not allowed
```

**Comment by sunaku** [comment]
Thanks for your report. :+1: This is [a known issue](https://github.com/rubygems/rubygems/issues/1448) that can be solved by upgrading to RubyGems 2.5.2:

    sudo gem update --system

See also #23

**Comment by fmeunier** [comment]
Thanks, that fixed it for me.

**Comment by sunaku** [comment]
Good news for the future: [Ruby 2.3.2+ now includes RubyGems 2.5.2](https://www.ruby-lang.org/en/news/2016/11/15/ruby-2-3-2-released/) so you won't hit this problem anymore.
