### ISSUE TITLE
Tildes disappear

### ISSUE THREAD

**Issue by rcorre** [sunaku/md2man#25]
Try rendering the [md2man example](https://raw.githubusercontent.com/sunaku/md2man/master/EXAMPLE.markdown).

Note that the `~` is replaced by whitespace.

The generated manpage has the following:

```
.PP
\fI\~/.foorc\fP
  Per user configuration file. See foo(5) for further details.
```

It works if you un-escape the `~`

**Comment by sunaku** [comment]
What manpage renderer are you using?  The tilde renders correctly for me with **mdocml** v1.14.1:

    md2man-roff EXAMPLE.markdown | man -l 
![maim](https://cloud.githubusercontent.com/assets/9863/25025123/d2ebf66e-2055-11e7-9e15-f8cb8a4a44c1.png)

**Comment by rcorre** [comment]
Sorry! this was a bug in [`go-md2man`](https://github.com/cpuguy83/go-md2man), I'm not sure how I ended up filing a bug against the wrong project! Thanks for taking a look anyways
